/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JORGE
 */
public class VistaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VistaCliente
     */
    public VistaAdministrador() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGestionPrestamos = new javax.swing.JButton();
        txtGestionPrestamos1 = new javax.swing.JButton();
        txtGestionPrestamos3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtGestionPrestamos.setBackground(new java.awt.Color(153, 153, 255));
        txtGestionPrestamos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGestionPrestamos.setText("Agregar tiquetes");
        txtGestionPrestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGestionPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGestionPrestamosActionPerformed(evt);
            }
        });

        txtGestionPrestamos1.setBackground(new java.awt.Color(153, 153, 255));
        txtGestionPrestamos1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGestionPrestamos1.setText("Ver lista");
        txtGestionPrestamos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtGestionPrestamos3.setBackground(new java.awt.Color(153, 153, 255));
        txtGestionPrestamos3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGestionPrestamos3.setText("Cerrar secion");
        txtGestionPrestamos3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGestionPrestamos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGestionPrestamos3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Vista Administrador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtGestionPrestamos3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtGestionPrestamos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGestionPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(txtGestionPrestamos)
                .addGap(31, 31, 31)
                .addComponent(txtGestionPrestamos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(txtGestionPrestamos3)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGestionPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGestionPrestamosActionPerformed
        // TODO add your handling code here:
        VistaAgregarTiquetes vistaAT;
        try {
            vistaAT = new VistaAgregarTiquetes();
            vistaAT.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(VistaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }

      
    }//GEN-LAST:event_txtGestionPrestamosActionPerformed

    private void txtGestionPrestamos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGestionPrestamos3ActionPerformed
        // TODO add your handling code here:
        VistaLogin vistal = new VistaLogin();
        vistal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtGestionPrestamos3ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton txtGestionPrestamos;
    private javax.swing.JButton txtGestionPrestamos1;
    private javax.swing.JButton txtGestionPrestamos3;
    // End of variables declaration//GEN-END:variables
}
