/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControlAgregarTiquete;
import excepciones.InvalidUserDataException;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Tiquete;
import modelo.TiqueteBuilder;

/**
 *
 * @author JORGE
 */
public class VistaAgregarTiquetes extends javax.swing.JFrame {

    ControlAgregarTiquete controlAT;
    TiqueteBuilder builder;
    ArrayList<Tiquete> tiquetes;

    /**
     * Creates new form VistaComprar
     */
    public VistaAgregarTiquetes() throws SQLException {
        initComponents();
        setLocationRelativeTo(this);
        controlAT = new ControlAgregarTiquete();
        builder = new TiqueteBuilder();
        tiquetes = controlAT.getTiquetes();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTiquetes = new javax.swing.JTable();
        txtGestionPrestamos1 = new javax.swing.JButton();
        txtGestionPrestamos2 = new javax.swing.JButton();
        txtDestino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Agregar");

        tablaTiquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Destino", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(tablaTiquetes);

        txtGestionPrestamos1.setBackground(new java.awt.Color(153, 153, 255));
        txtGestionPrestamos1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGestionPrestamos1.setText("Agregar");
        txtGestionPrestamos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGestionPrestamos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGestionPrestamos1ActionPerformed(evt);
            }
        });

        txtGestionPrestamos2.setBackground(new java.awt.Color(153, 153, 255));
        txtGestionPrestamos2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGestionPrestamos2.setText("Regresar");
        txtGestionPrestamos2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGestionPrestamos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGestionPrestamos2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Destino");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(122, 122, 122)
                .addComponent(txtGestionPrestamos1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtGestionPrestamos2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGestionPrestamos1)
                        .addGap(91, 91, 91)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtGestionPrestamos2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGestionPrestamos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGestionPrestamos1ActionPerformed
        // TODO add your handling code here:
        try {
            String destino = txtDestino.getText();
            java.util.Date fechaUtil = dateFecha.getDate(); // devuelve java.util.Date
            java.sql.Date fecha = new java.sql.Date(fechaUtil.getTime()); // conversión segura

            Tiquete tiquete = builder
                    .setDestino(destino)
                    .setFecha(fecha)
                    .getTiquete();

            controlAT.registrarTiquete(tiquete);
            JOptionPane.showMessageDialog(null, "El tiquete se ha agregado exitosamente");
            llenarTabla();
        } catch (InvalidUserDataException ex) {
            Logger.getLogger(VistaAgregarTiquetes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VistaAgregarTiquetes.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_txtGestionPrestamos1ActionPerformed

    private void txtGestionPrestamos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGestionPrestamos2ActionPerformed
        // TODO add your handling code here:
        VistaAdministrador vistaA = new VistaAdministrador();
        vistaA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtGestionPrestamos2ActionPerformed

    private void llenarTabla() throws SQLException {
        tiquetes = controlAT.getTiquetes();
        DefaultTableModel model = new DefaultTableModel(new String[]{"Id", "Destino", "Fecha"},
                tiquetes.size());
        tablaTiquetes.setModel(model);
        TableModel modelP = tablaTiquetes.getModel();
        for (int i = 0; i < tiquetes.size(); i++) {
            Tiquete tiquete = tiquetes.get(i);
            modelP.setValueAt(tiquete.getId(), i, 0);
            modelP.setValueAt(tiquete.getDestino(), i, 1);
            modelP.setValueAt(tiquete.getFecha(), i, 2);
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTiquetes;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JButton txtGestionPrestamos1;
    private javax.swing.JButton txtGestionPrestamos2;
    // End of variables declaration//GEN-END:variables
}
