/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControlAgregarTiquete;
import excepciones.InvalidUserDataException;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Tiquete;
import modelo.TiqueteBuilder;

/**
 *
 * @author JORGE
 */
public class VistaVerTiquetes extends javax.swing.JFrame {

    ControlAgregarTiquete controlAT;
    TiqueteBuilder builder;
    ArrayList<Tiquete> tiquetes;
    int idCliente;

    /**
     * Creates new form VistaComprar
     */
    public VistaVerTiquetes(int idCliente) throws SQLException {
        initComponents();
        setLocationRelativeTo(this);
        this.idCliente = idCliente;
        controlAT = new ControlAgregarTiquete();
        builder = new TiqueteBuilder();
        tiquetes = controlAT.getTiquetes();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTiquetes = new javax.swing.JTable();
        txtGestionPrestamos2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Tiquetes disponibles");

        tablaTiquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Destino", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(tablaTiquetes);

        txtGestionPrestamos2.setBackground(new java.awt.Color(153, 153, 255));
        txtGestionPrestamos2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGestionPrestamos2.setText("Regresar");
        txtGestionPrestamos2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGestionPrestamos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGestionPrestamos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtGestionPrestamos2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 614, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtGestionPrestamos2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGestionPrestamos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGestionPrestamos2ActionPerformed
        // TODO add your handling code here:
        VistaCliente VistaCliente = new VistaCliente(idCliente);
        VistaCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtGestionPrestamos2ActionPerformed

    private void llenarTabla() throws SQLException {
        tiquetes = controlAT.getTiquetes();
        DefaultTableModel model = new DefaultTableModel(new String[]{"Id", "Destino", "Fecha"},
                tiquetes.size());
        tablaTiquetes.setModel(model);
        TableModel modelP = tablaTiquetes.getModel();
        for (int i = 0; i < tiquetes.size(); i++) {
            Tiquete tiquete = tiquetes.get(i);
            modelP.setValueAt(tiquete.getId(), i, 0);
            modelP.setValueAt(tiquete.getDestino(), i, 1);
            modelP.setValueAt(tiquete.getFecha(), i, 2);
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTiquetes;
    private javax.swing.JButton txtGestionPrestamos2;
    // End of variables declaration//GEN-END:variables
}
